apiVersion: batch/v1
kind: Job
metadata:
  name: awscli-job-1
  namespace: team-riker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: awscli
    spec:
      restartPolicy: Never
      serviceAccountName: team-riker
      containers:
        - name: awscli
          image: public.ecr.aws/aws-cli/aws-cli
          command: ["aws", "s3", "ls"]
          resources:
            requests:
              memory: '64Mi'
              cpu: '250m'
            limits:
              memory: '128Mi'
              cpu: '500m'
      {{ if .Values.spec.karpenterInstanceProfile }}
      nodeSelector: # <- add nodeselector, toleration and spread constraitns
        team: default
        type: karpenter
      tolerations:
        - key: 'karpenter'
          operator: 'Exists'
          effect: 'NoSchedule'
      {{ end }}         
      tolerations:
        - key: 'karpenter'
          operator: 'Exists'
          effect: 'NoSchedule'  
